name: Build and Zip

on:
  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: ZIP
      run: zip -r codeinspectorx.zip ./build

    - name: Upload ZIP file
      uses: actions/upload-artifact@v2
      with:
        name: codeinspectorx
        path: codeinspectorx.zip
